version: "3.8"

services:
  tf-gpu:
    image: nvcr.io/nvidia/tensorflow:24.03-tf2-py3
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter_workspace:/workspace
    working_dir: /workspace
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.use_redirect_file=False --NotebookApp.custom_display_url=http://localhost:8888
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

