version: '3.8'

services:
  tf-gpu:
    build: .
    image: tf-gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter_workspace:/workspace
    working_dir: /workspace
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser
